/*
 * This file is derived from the AzerothCore Project.
 * Copyright (C) AzerothCore contributors.
 * Source: https://github.com/azerothcore/azerothcore-wotlk
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

// This file is generated by CMake. Do not edit it directly.

#cmakedefine TORTOISE_IS_DYNAMIC_MODULE_LOADER

#ifdef TORTOISE_IS_DYNAMIC_MODULE_LOADER
#  if defined(_WIN32)
#    define TORTOISE_MODULES_API extern "C" __declspec(dllexport)
#  else
#    define TORTOISE_MODULES_API extern "C" __attribute__((visibility("default")))
#  endif
#else
#  include "ModulesScriptLoader.h"
#  define TORTOISE_MODULES_API
#endif

@TORTOISE_MODULES_EXTRA_INCLUDES@
@TORTOISE_MODULES_FORWARD_DECL@

#ifdef TORTOISE_IS_DYNAMIC_MODULE_LOADER
TORTOISE_MODULES_API char const* GetScriptModule()
{
    return "@TORTOISE_CURRENT_MODULE_PROJECT@";
}
#endif

TORTOISE_MODULES_API void AddModulesScripts()
{
@TORTOISE_MODULES_INVOKE@
@TORTOISE_MODULES_EXTRA_INVOKE@
}

TORTOISE_MODULES_API char const* GetModulesBuildDirective()
{
    return "@TORTOISE_MODULES_BUILD_DIRECTIVE@";
}
